"""
e2e/scripts/07_adls_fabric.py
================================
End-to-end example: Microsoft Fabric Lakehouse (ADLS Gen2 / OneLake)
as the Iceberg warehouse, with archive to a cold-tier ADLS container.

Scenario
--------
  1. Create the tpch/orders Iceberg table in a Fabric Lakehouse via PyIceberg
     using the Fabric REST endpoint or the ADLS Gen2 storage path directly.
  2. Load 10 monthly Parquet partitions (generated by 01_generate_tpch.py).
  3. Archive the 5 oldest months to a cold ADLS container.
  4. Restore one archived month back to the Fabric Lakehouse.
  5. (Optional) Verify via a Fabric SQL Analytics Endpoint query.

Prerequisites
-------------
  pip install pyiceberg[adls] azure-storage-blob azure-identity pyarrow duckdb

Required environment variables:
  AZURE_STORAGE_ACCOUNT   e.g. myfabricaccount
  AZURE_STORAGE_KEY       account key (or rely on DefaultAzureCredential)
  FABRIC_WORKSPACE_ID     Fabric workspace GUID
  FABRIC_LAKEHOUSE_ID     Fabric Lakehouse GUID
  NESSIE_URI              http://your-nessie:19120  (optional, for catalog)
  OAUTH_URL               http://your-oauth/oauth2/token (optional)
  OAUTH_CLIENT_ID
  OAUTH_CLIENT_SECRET

Usage:
  export AZURE_STORAGE_ACCOUNT=myfabricaccount
  export AZURE_STORAGE_KEY=<key>
  export FABRIC_WORKSPACE_ID=<guid>
  export FABRIC_LAKEHOUSE_ID=<guid>

  python e2e/scripts/07_adls_fabric.py --help
  python e2e/scripts/07_adls_fabric.py create-table
  python e2e/scripts/07_adls_fabric.py archive --execute
  python e2e/scripts/07_adls_fabric.py restore --month 2024-03 --confirm
  python e2e/scripts/07_adls_fabric.py verify
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

# ── Azure / Fabric connection constants ──────────────────────────────────────

AZURE_ACCOUNT      = os.environ.get("AZURE_STORAGE_ACCOUNT", "")
AZURE_KEY          = os.environ.get("AZURE_STORAGE_KEY", "")
FABRIC_WORKSPACE   = os.environ.get("FABRIC_WORKSPACE_ID", "")
FABRIC_LAKEHOUSE   = os.environ.get("FABRIC_LAKEHOUSE_ID", "")
NESSIE_URI         = os.environ.get("NESSIE_URI", "")
OAUTH_URL          = os.environ.get("OAUTH_URL", "")
OAUTH_CLIENT_ID    = os.environ.get("OAUTH_CLIENT_ID", "sync-service")
OAUTH_CLIENT_SECRET= os.environ.get("OAUTH_CLIENT_SECRET", "")

# Fabric OneLake path — Iceberg tables live under the Lakehouse "Tables" section
# abfss://fabric@<account>.dfs.core.windows.net/workspaces/<ws>/lakehouses/<lh>/Tables
FABRIC_CONTAINER = "fabric"
ONELAKE_HOST     = f"{AZURE_ACCOUNT}.dfs.core.windows.net"
LAKEHOUSE_ROOT   = (
    f"abfss://{FABRIC_CONTAINER}@{ONELAKE_HOST}"
    f"/workspaces/{FABRIC_WORKSPACE}/lakehouses/{FABRIC_LAKEHOUSE}/Tables"
)

# Cold storage: separate container (archive) in the same account
COLD_CONTAINER   = "archive"
ARCHIVE_ROOT     = f"abfss://{COLD_CONTAINER}@{ONELAKE_HOST}/iceberg-cold"

NAMESPACE = "tpch"
TABLE     = "orders"
DATA_DIR  = Path("e2e/data/orders")

# ── ADLS kwargs helper ───────────────────────────────────────────────────────

def adls_kwargs() -> dict:
    """Return storage kwargs for the ADLS Gen2 backend."""
    if AZURE_KEY:
        return {"account_name": AZURE_ACCOUNT, "account_key": AZURE_KEY}
    # Fall back to DefaultAzureCredential (managed identity / az login / env SP)
    return {"account_name": AZURE_ACCOUNT, "use_default_credential": True}


def catalog_kwargs() -> dict:
    return {
        "nessie_uri":          NESSIE_URI,
        "nessie_ref":          "main",
        "oauth_url":           OAUTH_URL,
        "oauth_client_id":     OAUTH_CLIENT_ID,
        "oauth_client_secret": OAUTH_CLIENT_SECRET,
    }


# ── Guard: require env vars ───────────────────────────────────────────────────

def require_env() -> None:
    missing = [v for v in ("AZURE_STORAGE_ACCOUNT", "FABRIC_WORKSPACE_ID", "FABRIC_LAKEHOUSE_ID")
               if not os.environ.get(v)]
    if missing:
        print(f"ERROR: Required environment variables not set: {', '.join(missing)}")
        print("\nExport them before running:")
        for v in missing:
            print(f"  export {v}=<value>")
        sys.exit(1)


# ── Step 1: Create Iceberg table in Fabric Lakehouse ─────────────────────────

def cmd_create_table(args) -> None:
    """
    Create the tpch.orders Iceberg table in the Fabric Lakehouse.

    Microsoft Fabric exposes OneLake storage as a standard ADLS Gen2 endpoint.
    PyIceberg writes metadata.json and Parquet data files directly to OneLake
    — Fabric then auto-discovers the Iceberg table in the SQL Analytics Endpoint.

    Fabric Lakehouse Iceberg path layout:
      Tables/
        tpch/
          orders/
            metadata/
              v00001.metadata.json
              version-hint.text
            data/
              order_month=2024-01/
                00000-0-<uuid>.parquet
    """
    import pyarrow.parquet as pq
    from pyiceberg.catalog.sql import SqlCatalog
    from pyiceberg.partitioning import PartitionField, PartitionSpec
    from pyiceberg.schema import Schema
    from pyiceberg.transforms import IdentityTransform
    from pyiceberg.types import (
        DateType, DecimalType, IntegerType, LongType, NestedField, StringType,
    )

    require_env()

    print("=== Step 1: Create Iceberg Table in Fabric Lakehouse ===\n")
    print(f"  OneLake root : {LAKEHOUSE_ROOT}")

    schema = Schema(
        NestedField(1,  "order_key",      LongType(),           required=True),
        NestedField(2,  "customer_key",   LongType()),
        NestedField(3,  "order_status",   StringType()),
        NestedField(4,  "total_price",    DecimalType(15, 2)),
        NestedField(5,  "order_date",     DateType()),
        NestedField(6,  "order_priority", StringType()),
        NestedField(7,  "clerk",          StringType()),
        NestedField(8,  "ship_priority",  IntegerType()),
        NestedField(9,  "comment",        StringType()),
        NestedField(10, "order_month",    StringType()),
    )
    partition_spec = PartitionSpec(
        PartitionField(source_id=10, field_id=1000,
                       transform=IdentityTransform(), name="order_month"),
    )

    # PyIceberg with ADLS storage backend
    # We use an in-process SQL catalog backed by SQLite to manage table pointers;
    # the actual data and metadata live in OneLake (ADLS Gen2).
    catalog = SqlCatalog(
        "fabric_local",
        **{
            "uri": "sqlite:///e2e/fabric_catalog.db",  # local pointer store
            "adls.account-name":     AZURE_ACCOUNT,
            "adls.account-key":      AZURE_KEY or "",
            # If using service principal instead of account key:
            # "adls.tenant-id":      os.getenv("AZURE_TENANT_ID"),
            # "adls.client-id":      os.getenv("AZURE_CLIENT_ID"),
            # "adls.client-secret":  os.getenv("AZURE_CLIENT_SECRET"),
        },
    )

    # Create namespace
    if (NAMESPACE,) not in catalog.list_namespaces():
        catalog.create_namespace(NAMESPACE)
        print(f"  Created namespace '{NAMESPACE}'")

    full_name = f"{NAMESPACE}.{TABLE}"
    if catalog.table_exists(full_name):
        print(f"  Table '{full_name}' already exists — loading.")
        table = catalog.load_table(full_name)
    else:
        table = catalog.create_table(
            full_name,
            schema=schema,
            partition_spec=partition_spec,
            location=f"{LAKEHOUSE_ROOT}/{NAMESPACE}/{TABLE}",
            properties={
                "write.format.default": "parquet",
                "write.parquet.compression-codec": "snappy",
            },
        )
        print(f"  Created table '{full_name}'")
        print(f"  Location       : {table.location()}")

    # Load monthly partitions
    part_dirs = sorted(DATA_DIR.glob("order_month=*"))
    if not part_dirs:
        print(f"\nNo Parquet files found under {DATA_DIR}.")
        print("Run 01_generate_tpch.py first.\n")
        sys.exit(1)

    print(f"\nLoading {len(part_dirs)} monthly partitions …")
    for part_dir in part_dirs:
        month = part_dir.name.split("=", 1)[1]
        files = list(part_dir.glob("*.parquet"))
        if not files:
            continue
        arrow_tbl = pq.read_table(files[0])
        table.append(arrow_tbl)
        print(f"  order_month={month}  {len(arrow_tbl):>10,} rows → OneLake")

    print(f"\nTable '{full_name}' loaded into Fabric Lakehouse.")
    print(
        "\nFabric SQL Analytics Endpoint will auto-discover the table."
        "\nIn Fabric portal: Lakehouse → SQL Analytics Endpoint → tpch.orders"
    )


# ── Step 2: Archive old partitions ───────────────────────────────────────────

def cmd_archive(args) -> None:
    """
    Archive the 5 oldest monthly snapshots from Fabric Lakehouse (OneLake)
    to the cold-tier ADLS container.
    """
    require_env()

    from iceberg_sync.archive.archiver import IcebergArchiver
    from iceberg_sync.archive.config import (
        ArchiveJobConfig, ADLSConfig, CatalogConfig, TransferConfig,
    )

    dry_run = not args.execute
    print(f"=== Archive Fabric Lakehouse → Cold Storage [{'EXECUTE' if args.execute else 'DRY-RUN'}] ===\n")
    print(f"  Source (OneLake) : {LAKEHOUSE_ROOT}")
    print(f"  Archive (cold)   : {ARCHIVE_ROOT}")

    adls = ADLSConfig(**adls_kwargs())
    cfg = ArchiveJobConfig(
        source_root=LAKEHOUSE_ROOT,
        table=f"{NAMESPACE}/{TABLE}",
        archive_root=ARCHIVE_ROOT,
        older_than="150d",
        min_snapshots_to_keep=5,
        delete_after_archive=True,
        dry_run=dry_run,
        source_adls=adls,
        archive_adls=adls,
        catalog=CatalogConfig(**catalog_kwargs()) if NESSIE_URI else CatalogConfig(),
        transfer=TransferConfig(parallelism=8),
    )

    archiver = IcebergArchiver.from_config(cfg)
    result = archiver.archive_table(f"{NAMESPACE}/{TABLE}", dry_run=dry_run)

    print()
    _print_archive_result(result)

    if dry_run:
        print("\n[DRY-RUN] Re-run with --execute to apply.\n")


# ── Step 3: Restore from cold storage back to Fabric ─────────────────────────

def cmd_restore(args) -> None:
    """
    Restore an archived monthly partition from cold storage back to
    the Fabric Lakehouse OneLake path.
    """
    require_env()

    from iceberg_sync.archive.config import (
        ADLSConfig, CatalogConfig, RestoreJobConfig, TransferConfig,
    )
    from iceberg_sync.archive.restorer import IcebergRestorer

    print(f"=== Restore Cold Storage → Fabric Lakehouse [{'EXECUTE' if args.confirm else 'PLAN'}] ===\n")
    print(f"  Archive (cold)   : {ARCHIVE_ROOT}")
    print(f"  Target (OneLake) : {LAKEHOUSE_ROOT}")
    print(f"  Month to restore : {args.month}")

    adls = ADLSConfig(**adls_kwargs())
    cfg = RestoreJobConfig(
        archive_root=ARCHIVE_ROOT,
        table=f"{NAMESPACE}/{TABLE}",
        target_root=LAKEHOUSE_ROOT,
        as_of=args.as_of,
        partitions=[{"order_month": args.month}],
        mode="replace",
        conflict_strategy="skip",
        archive_adls=adls,
        target_adls=adls,
        catalog=CatalogConfig(**catalog_kwargs()) if NESSIE_URI else CatalogConfig(),
        transfer=TransferConfig(parallelism=8),
    )

    restorer = IcebergRestorer.from_config(cfg)

    print("\n--- Available Archive Snapshots ---")
    restorer.list_snapshots()

    print(f"\n--- Restore Plan: order_month={args.month} ---")
    plan = restorer.plan()

    if not args.confirm:
        print("\n[PLAN ONLY] Add --confirm to execute.\n")
        return

    print("\nExecuting restore …")
    result = restorer.execute(plan)

    print()
    if result.success:
        print(f"  Files restored  : {result.files_copied}")
        print(f"  Bytes restored  : {result.bytes_copied:,}")
        print(f"  New metadata    : {result.new_metadata_uri}")
        print(
            "\nPartition restored to OneLake. "
            "Refresh the Fabric SQL Analytics Endpoint to query it.\n"
        )
    else:
        print("Restore failed:")
        for e in result.errors:
            print(f"  • {e}")
        sys.exit(1)


# ── Step 4: Verify via Fabric SQL Analytics Endpoint ─────────────────────────

def cmd_verify(args) -> None:
    """
    Verify the restored partition is visible.

    Option A — PyIceberg direct (reads from OneLake):
      Works without Fabric portal access.

    Option B — Fabric SQL Analytics Endpoint (T-SQL):
      Shown as a printed SQL snippet you can run in the Fabric portal or
      via pyodbc/sqlalchemy with your Fabric connection string.
    """
    require_env()

    print("=== Verify Restored Partition ===\n")

    # Option A: PyIceberg direct read
    print("--- Option A: Direct PyIceberg Read from OneLake ---")
    try:
        from pyiceberg.catalog.sql import SqlCatalog
        catalog = SqlCatalog(
            "fabric_local",
            **{
                "uri": "sqlite:///e2e/fabric_catalog.db",
                "adls.account-name": AZURE_ACCOUNT,
                "adls.account-key": AZURE_KEY or "",
            },
        )
        table = catalog.load_table(f"{NAMESPACE}.{TABLE}")
        arrow_tbl = table.scan(
            row_filter=f"order_month = '{args.month}'"
        ).to_arrow()
        row_count = len(arrow_tbl)
        print(f"  order_month={args.month}  {row_count:,} rows visible ✓" if row_count > 0
              else f"  WARNING: 0 rows found for order_month={args.month}")
    except Exception as exc:
        print(f"  PyIceberg read failed: {exc}")

    # Option B: Fabric SQL snippet
    print(
        "\n--- Option B: Fabric SQL Analytics Endpoint ---\n"
        "Run this T-SQL in the Fabric portal (SQL Analytics Endpoint tab):\n"
        "\n"
        "  -- Count rows in the restored partition\n"
        f"  SELECT order_month, COUNT(*) AS row_count\n"
        f"  FROM   tpch.orders\n"
        f"  WHERE  order_month = '{args.month}'\n"
        f"  GROUP BY order_month;\n"
        "\n"
        "  -- Confirm metadata pointer\n"
        f"  SELECT TOP 5 *\n"
        f"  FROM   tpch.orders\n"
        f"  WHERE  order_month = '{args.month}'\n"
        f"  ORDER BY order_date;\n"
    )

    # Option C: via pyodbc (if Fabric ODBC driver installed)
    print(
        "--- Option C: pyodbc (requires Fabric JDBC/ODBC driver) ---\n"
        "\n"
        "  import pyodbc\n"
        "  conn_str = (\n"
        "      'Driver={ODBC Driver 18 for SQL Server};'\n"
        "      'Server=<workspace>.datawarehouse.fabric.microsoft.com;'\n"
        "      'Database=<lakehouse_name>;'\n"
        "      'Authentication=ActiveDirectoryInteractive;'\n"
        "  )\n"
        "  with pyodbc.connect(conn_str) as conn:\n"
        "      cur = conn.cursor()\n"
        f"     cur.execute(\"SELECT COUNT(*) FROM tpch.orders WHERE order_month = '{args.month}'\")\n"
        "      print(cur.fetchone())\n"
    )


# ── Helpers ───────────────────────────────────────────────────────────────────

def _print_archive_result(result) -> None:
    print("─" * 50)
    print(f"  Table             : {result.table}")
    print(f"  Snapshots archived: {result.snapshots_archived}")
    print(f"  Snapshots skipped : {result.snapshots_skipped}")
    print(f"  Files copied      : {result.files_copied}")
    print(f"  Bytes copied      : {result.bytes_copied:,}")
    print(f"  Success           : {result.success}")
    print("─" * 50)
    if result.errors:
        print("\nErrors:")
        for e in result.errors:
            print(f"  • {e}")


# ── CLI entry point ───────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(
        description="ADLS Gen2 / Microsoft Fabric Iceberg archive & restore demo.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    sub = parser.add_subparsers(dest="cmd", required=True)

    # create-table
    p_create = sub.add_parser("create-table", help="Create Iceberg table in Fabric Lakehouse")
    p_create.set_defaults(func=cmd_create_table)

    # archive
    p_arch = sub.add_parser("archive", help="Archive old partitions to cold ADLS container")
    p_arch.add_argument("--execute", action="store_true",
                        help="Execute archive (default: dry-run)")
    p_arch.set_defaults(func=cmd_archive)

    # restore
    p_rest = sub.add_parser("restore", help="Restore partition from cold ADLS to Fabric")
    p_rest.add_argument("--month",   default="2024-03",
                        help="Partition to restore as YYYY-MM (default: 2024-03)")
    p_rest.add_argument("--as-of",  default="2024-04-01",
                        help="Restore snapshot as of this date (default: 2024-04-01)")
    p_rest.add_argument("--confirm", action="store_true",
                        help="Execute the restore (default: plan only)")
    p_rest.set_defaults(func=cmd_restore)

    # verify
    p_ver = sub.add_parser("verify", help="Verify the restored partition is visible")
    p_ver.add_argument("--month", default="2024-03",
                       help="Partition to check (default: 2024-03)")
    p_ver.set_defaults(func=cmd_verify)

    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
